In [5]:
nums = [1,2,3,4,5,6,7,8]
result = map(lambda x: x%2 == 0, nums)
result

In [6]:
result = list(result)
result

[False, True, False, True, False, True, False, True]

In [8]:
from collections import deque


d = deque([1,2,3,4,5], maxlen=5)
d.appendleft(0)
print(d)
d.append(6)
print(d)

deque([0, 1, 2, 3, 4], maxlen=5)
deque([1, 2, 3, 4, 6], maxlen=5)


In [13]:
l = [3,4,6,5,1,6,2]
q = sorted(l)
print(l)
print(q)
l.sort()
print(l)

[3, 4, 6, 5, 1, 6, 2]
[1, 2, 3, 4, 5, 6, 6]
[1, 2, 3, 4, 5, 6, 6]


In [34]:
from functools import reduce
nums = [[1,2,3], [3,4,5]]
result = reduce(lambda x,y: [elem for elem in x]+[elem for elem in y], nums)
result

[1, 2, 3, 3, 4, 5]

In [37]:
x = [elem for elem in range(69)]
for x in x:
    if (x + 1)*3/3%3 != (x+1)%3:
        print(x)    

In [72]:
class balls:
    def __init__(self, color, size):
        self.color = color
        self.size = size
    def __str__(self):
        return f'{self.color} ball of size {self.size}'
    def __iter__(self):
        return iter([self.color, self.size])
    def __next__(self):
        return next([self.color, self.size])
    
    
b = balls('red', 5)
mtitr = iter(b)
print(mtitr)
print(next(mtitr))
print(*b)
str(b)

red
red 5


'red ball of size 5'

In [73]:
f = open("test.txt", "r")
help(f)

Help on TextIOWrapper in module _io object:

class TextIOWrapper(_TextIOBase)
 |  TextIOWrapper(buffer, encoding=None, errors=None, newline=None, line_buffering=False, write_through=False)
 |
 |  Character and line based layer over a BufferedIOBase object, buffer.
 |
 |  encoding gives the name of the encoding that the stream will be
 |  decoded or encoded with. It defaults to locale.getencoding().
 |
 |  errors determines the strictness of encoding and decoding (see
 |  help(codecs.Codec) or the documentation for codecs.register) and
 |  defaults to "strict".
 |
 |  newline controls how line endings are handled. It can be None, '',
 |  '\n', '\r', and '\r\n'.  It works as follows:
 |
 |  * On input, if newline is None, universal newlines mode is
 |    enabled. Lines in the input can end in '\n', '\r', or '\r\n', and
 |    these are translated into '\n' before being returned to the
 |    caller. If it is '', universal newline mode is enabled, but line
 |    endings are returned to the 

In [77]:
s = {5,2,5,1,6,8.7,142,84}
q = set([5,2,5,1,6,8.7,142,84])
print(s)
print(q)
print(type(s))
print(type(q))
help(s)

{1, 2, 84, 5, 6, 8.7, 142}
{1, 2, 5, 6, 8.7, 142, 84}
<class 'set'>
<class 'set'>
Help on set object:

class set(object)
 |  set() -> new empty set object
 |  set(iterable) -> new set object
 |
 |  Build an unordered collection of unique elements.
 |
 |  Methods defined here:
 |
 |  __and__(self, value, /)
 |      Return self&value.
 |
 |  __contains__(...)
 |      x.__contains__(y) <==> y in x.
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __iand__(self, value, /)
 |      Return self&=value.
 |
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __ior__(self, value, /)
 |      Return self|=value.
 |
 |  __isub__(self, value, /)
 |      Return self-=value.
 |
 |  __iter__(self, /)
 |      Implement iter(self).
 |
 | 

In [85]:
f = open("test.txt", "r")
with f:
    print(f.read())
print(f.read())

hehe
lmao
this is a line
flag{come find me}


ValueError: I/O operation on closed file.

In [8]:
import pandas as pd
df = pd.DataFrame({"Fruit": ["banana", "apple", "cow", "fuck", "banana", "fuck", "milk", "cum", "cum", "cum"]})
cock = pd.get_dummies(df.Fruit)
pd.concat([df, cock], axis=1)



Fruit  apple  banana    cow    cum   fuck   milk
0  banana  False    True  False  False  False  False
1   apple   True   False  False  False  False  False
2     cow  False   False   True  False  False  False
3    fuck  False   False  False  False   True  False
4  banana  False    True  False  False  False  False
5    fuck  False   False  False  False   True  False
6    milk  False   False  False  False  False   True
7     cum  False   False  False   True  False  False
8     cum  False   False  False   True  False  False
9     cum  False   False  False   True  False  False

In [9]:
import pandas as pd
import numpy as np
df = pd.DataFrame(
    {
        "Fruit": ["banana", "apple", "pineapple", "orange"],
        "Vegetable": ["onion", "carrot", "tomato", np.nan],
        "Stationary": ["Pen", "pencil", "sharpener", np.nan],
    }
    ,
    index=["Fruit", "Vegetable", "Stationary", "Bacchiri kukki la"]
)
df

Fruit Vegetable Stationary
Fruit                 banana     onion        Pen
Vegetable              apple    carrot     pencil
Stationary         pineapple    tomato  sharpener
Bacchiri kukki la     orange       NaN        NaN

In [26]:
df[[True, False, True, False]]

Fruit Vegetable Stationary
Fruit          banana     onion        Pen
Stationary  pineapple    tomato  sharpener

In [2]:
from sklearn.preprocessing import normalize
from sklearn.preprocessing import Normalizer

# Create an instance of the Normalizer
normalizer = Normalizer(norm='l2')

# Sample data
data = [[1, 2, 3], [4, 5, 6]]

# Fit the normalizer to the data and transform it
normalized_data = normalizer.transform(data)

print(normalized_data)

[[0.26726124 0.53452248 0.80178373]
 [0.45584231 0.56980288 0.68376346]]


In [2]:
import numpy as np
a = np.array(2)
a

array(2)

In [6]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
e = np.array([2], ndmin=62)
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

0
1
2
3
62


In [59]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)


None
[1 2 3 4 5]


In [60]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

    Return evenly spaced values within a given interval.

    ``arange`` can be called with a varying number of positional arguments:

    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.

    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.

    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.

    See the Warn